name: Quibble and Phan

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*.*'
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        mediawiki-version:
          - master
          - REL1_43
        stage:
          - phan
          # - coverage # We really need this coverage for a skin?
          - phpunit-unit
          - phpunit
          - phpunit-parallel
          - phpunit-standalone
          - npm-test
          - composer-test
          - selenium
          # - qunit
          # - api-testing

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        if: matrix.stage == 'phpunit' || matrix.stage == 'selenium'
        with:
          node-version: '16'
          cache: npm

      - run: npm install
        if: matrix.stage == 'phpunit' || matrix.stage == 'selenium'

      - uses: femiwiki/quibble-action@v1
        id: quibble
        with:
          stage: ${{ matrix.stage }}
          quibble-docker-image: quibble-buster-php81
          # There is no quibble-buster-php81-coverage yet
          coverage-docker-image: quibble-buster-php74-coverage
          phan-docker-image: mediawiki-phan-php81
          mediawiki-version: ${{ matrix.mediawiki-version }}
          exclude-extensions: ${{ steps.exclude-extensions.outputs.list }}

      - name: Upload coverage to Codecov
        if: ${{ matrix.stage == 'coverage' }}
        uses: codecov/codecov-action@v3
        with:
          directory: ${{ steps.quibble.outputs.coverage }}
